"""Defensive remediation script generator for correcting dangling DNS records.

Generates executable AWS Route53 CLI, Cloudflare API, and BIND zone commands
to safely remove or update vulnerable dangling DNS records.
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

try:
    from src.exporter import Finding
except ImportError:
    from exporter import Finding


def generate_aws_route53_remediation(findings: Sequence[Finding], hosted_zone_id: str = "YOUR_HOSTED_ZONE_ID") -> str:
    """Generate AWS Route 53 CLI batch change-resource-record-sets JSON and delete command."""
    changes = []
    for f in findings:
        target_name = f.hostname.rstrip(".") + "."
        cname_val = (f.cname or "unclaimed.target.net").rstrip(".") + "."
        changes.append(f"""    {{
      "Action": "DELETE",
      "ResourceRecordSet": {{
        "Name": "{target_name}",
        "Type": "CNAME",
        "TTL": 300,
        "ResourceRecords": [
          {{ "Value": "{cname_val}" }}
        ]
      }}
    }}""")

    changes_json = ",\n".join(changes)
    json_payload = f"""{{
  "Comment": "Remediation: Delete dangling CNAME records susceptible to takeover",
  "Changes": [
{changes_json}
  ]
}}"""

    script = f"""# ==============================================================================
# AWS Route 53 Defensive Remediation Script
# ==============================================================================
# Instructions:
# 1. Verify your AWS CLI credentials: aws sts get-caller-identity
# 2. Set your hosted zone ID:
ZONE_ID="{hosted_zone_id}"

# 3. Apply the deletion batch to Route 53:
cat << 'EOF' > /tmp/route53_delete_batch.json
{json_payload}
EOF

aws route53 change-resource-record-sets --hosted-zone-id "$ZONE_ID" --change-batch file:///tmp/route53_delete_batch.json
"""
    return script


def generate_cloudflare_remediation(findings: Sequence[Finding]) -> str:
    """Generate Cloudflare API commands to purge dangling DNS records."""
    commands = [
        "# ==============================================================================",
        "# Cloudflare DNS Defensive Remediation Playbook",
        "# ==============================================================================",
        "# Export your Cloudflare API token and Zone ID:",
        'export CF_API_TOKEN="YOUR_CLOUDFLARE_API_TOKEN"',
        'export CF_ZONE_ID="YOUR_ZONE_ID"',
        "",
        "# List and delete dangling DNS records:",
    ]

    for f in findings:
        commands.append(f"""# Host: {f.hostname} ({f.service or 'Unclaimed'})
# Step 1: Look up record ID
RECORD_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records?name={f.hostname}" \\
     -H "Authorization: Bearer $CF_API_TOKEN" \\
     -H "Content-Type: application/json" | grep -o '"id":"[^"]*' | head -n 1 | cut -d'"' -f4)

# Step 2: Delete dangling record
if [ -n "$RECORD_ID" ]; then
    echo "Deleting dangling record for {f.hostname} (ID: $RECORD_ID)..."
    curl -s -X DELETE "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records/$RECORD_ID" \\
         -H "Authorization: Bearer $CF_API_TOKEN" \\
         -H "Content-Type: application/json"
fi
""")

    return "\n".join(commands)


def generate_bind_remediation(findings: Sequence[Finding]) -> str:
    """Generate standard BIND / RFC 1035 zone file comment-out diff."""
    lines = [
        "; ==============================================================================",
        "; BIND / Zone File Defensive Remediation",
        "; Remove or comment out the following dangling records from your zone file:",
        "; ==============================================================================",
        "",
    ]
    for f in findings:
        cname_val = (f.cname or "unclaimed.target.net").rstrip(".") + "."
        lines.append(f"; [TAKEVOER RISK: {f.service or 'Unclaimed'}] Reason: {f.reason}")
        lines.append(f"; - {f.hostname}. IN CNAME {cname_val}")
        lines.append("")
    return "\n".join(lines)


def export_remediation_playbook(path: Path, findings: Sequence[Finding]) -> None:
    """Export complete defensive remediation playbooks to disk."""
    path.parent.mkdir(parents=True, exist_ok=True)
    content = [
        "#!/usr/bin/env bash",
        "# Subdomain Takeover Defensive Remediation Playbook",
        "# Auto-generated by Rudra Pratap Dalei - Red Team Subdomain Scanner",
        "",
        generate_aws_route53_remediation(findings),
        "",
        generate_cloudflare_remediation(findings),
        "",
        generate_bind_remediation(findings),
    ]
    path.write_text("\n".join(content), encoding="utf-8")
